CREATE TABLE IF NOT EXISTS talk(
id INT PRIMARY KEY AUTO_INCREMENT,
nowdate DATETIME,
name VARCHAR(10),
comment VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS authorities(
username VARCHAR(50) PRIMARY KEY,
authority VARCHAR(100) NOT NULL
);
